#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if command -v systemctl > /dev/null 2>&1; then
        systemctl stop gotify.service || true
        systemctl disable gotify.service || true
    fi
fi

exit 0
